### ISSUE TITLE
todo: Automatic multiplication detection.

### ISSUE THREAD

**Issue by datawater** [datawater/L#5]
Currently the parser can only detect multiplication through the operand `*` and transforms `(a)(b) ==> (a) * (b)`.
Being able to detect multiplication in examples like this, would be a great addition:

```
n(n-1) ==> n * (n-1)
abc ==> a * b * c
2pi ==> 2 * pi
etc.
```

**Comment by Sachin0611** [comment]
Hey! I am a beginner in open source but I have done a lot of programming in c++, java. I would like to fix this issue. Can you please guide further?

**Comment by datawater** [comment]
> Hey! I am a beginner in open source but I have done a lot of programming in c++, java. I would like to fix this issue. Can you please guide further?

Of course, I'd be happy to guide you on how to address this issue! It's great to hear that you're interested in contributing to L.

For this particular issue, the goal is to enhance the parser's ability to automatically detect multiplication in various formats, beyond just using the * operand. This could involve recognizing patterns like n(n-m) and transforming it to n * (n-m) or identifying sequences of characters like abc and converting it to a * b * c. Our parser currently doesn't support variables, so an example with actual numbers would be something like transforming 2(2-5) into 2 * (2-5) or transforming 2pi into 2 * pi.

I want to mention that the codebase is currently not well-documented and is still in an active development state. This means that you might encounter parts of the code that are not very clear or complete. If you run into any issues or have questions, please don't hesitate to reach out to me.

**Comment by Sachin0611** [comment]
Thanks for the explanation. I will try to fix it and let you know.

**Comment by Sachin0611** [comment]
![image](https://github.com/datawater/L/assets/77977246/de4bad1e-af48-4e7d-850f-3e0cbdd06906)

Getting these type of errors across all the .hpp files. Any fix?

**Comment by datawater** [comment]
> ![image](https://user-images.githubusercontent.com/77977246/263715661-de4bad1e-af48-4e7d-850f-3e0cbdd06906.png)
> 
> Getting these type of errors across all the .hpp files. Any fix?

Check if `<type_traits>` is included, also the c++ standard should be c++20

**Comment by datawater** [comment]
Partially implemented by 981bcc2, added `n(n - 1)` like multiplication detection.

**Comment by datawater** [comment]
Fixed by [d8c5349](https://github.com/datawater/L/commit/d8c5349c57c51cf627832d51d8ca44c07ff4851e)
